#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="vim,tmux,i3,zsh,bin,nvim"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES 

pushd $DOTFILES/ubuntu
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
  echo "Installing $folder"
  stow -t ~ -D $folder
  stow -t ~ $folder
done
popd
