#!/usr/bin/env bash

pushd $DOTFILES/ubuntu-srv-dev
STOW_FOLDERS="vim,tmux,bash,git,nvim,zsh,bin"
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
  echo "Removing $folder"
  stow -t ~ -D $folder 
done
popd
